catalog/cars/urls.py
from rest_framework import routers
from django.urls import path, include
from .views import docs, about, contacts, ShowCar, AddCar, CarsHome, LoginUser, \
    RegisterUser, logout_user, infaclientu
from .viewsets import CarsViewSet

router = routers.DefaultRouter()
router.register(r'cars', CarsViewSet, basename='cars')

urlpatterns = [
    # path('', index, name='home'),
    # path('', AutoHome.as_view(), name='home'),
    # path('glav/', glav, name='glav'),
    path('docs/<slug:doc>/', docs, name='docs'),
    # path('auto/', auto, name='auto'),
    path('', CarsHome.as_view(), name='auto'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('infa/', infaclientu, name='infa'),
    # path('car/<slug:car_slug>/', show_cars, name='car'),
    path('car/<slug:car_slug>/', ShowCar.as_view(), name='car'),
    # path('addcar/', addcar, name='addcar'),
    path('addcar/', AddCar.as_view(), name='addcar'),
    # path('addcar2/', AddCar2.as_view(), name='addcar2'),
    path('login/', LoginUser.as_view(), name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', logout_user, name='logout'),
    # path('gradebook/', Gradebook.as_view(), name='gradebook'),
    # path('api/v1/students/', StudentAPIView.as_view()),
    # path('api/v1/groups/', GroupAPIView.as_view()),
    # path('api/v1/student/<int:pk>/', StudentAPIDetailView.as_view()),
    # path('api/v1/students/', StudentViewSet.as_view({'get': 'list'})),
    # path('api/v1/student/<int:pk>/', StudentViewSet.as_view({'put': 'update'})),
    path('api/v1/', include(router.urls)),
]

catalog/catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from catalog import settings
# from cars.views import model #cars


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
    # path('model/<slug:model>/', model),
    # path('marka/<int:marki>/', marki),
    #path('cars/', cars),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/cars/models.py
from datetime import date
from django.db import models
from django.urls import reverse
import random
import string
from django.utils.text import slugify
from randomslugfield import RandomSlugField
from django.db.models import F, Func
from rest_framework.authtoken.admin import User


# from django.db.models.functions import Format

class Cars(models.Model):
    # modeli = models.CharField(verbose_name='Модель', max_length=50)
    marka = models.ForeignKey('Marka', on_delete=models.CASCADE, verbose_name='Марка:')
    model = models.ForeignKey('Model', on_delete=models.CASCADE, verbose_name='Модель:')
    # markis = models.CharField(verbose_name='Марка', max_length=50)
    cuzov = models.ForeignKey('Cuzov', on_delete=models.CASCADE, verbose_name='Тип кузова:')
    cvet = models.CharField(verbose_name='Цвет:', max_length=50)
    vin = models.CharField(verbose_name='VIN:', max_length=50)
    compl = models.CharField(verbose_name='Комплектация:', max_length=50, null=True, blank=True)
    data = models.ForeignKey('Data', on_delete=models.CASCADE, verbose_name='Год выпуска:')
    # date = models.DateField(verbose_name='Год', default=date(2023, 1, 1))       # как выводить формат даты date = models.DateField(verbose_name='Год', default=date(2023, 1, 1))
    nalli = models.BooleanField(verbose_name='В продаже', default=False)
    price = models.IntegerField(verbose_name='Желаемая цена:')
    probeg = models.IntegerField(verbose_name='Пробег:')
    email_mg = models.EmailField(verbose_name='e-mail Менеджера', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True, null=True)
    updated_at = models.DateTimeField(verbose_name='Дата изменения', auto_now=True, null=True)
    objects = models.Model
    trans = models.ForeignKey('Trans', on_delete=models.CASCADE, verbose_name='Трансмисия:')
    obem = models.ForeignKey('Obem', on_delete=models.CASCADE, verbose_name='Объём двигателя:')
    top = models.ForeignKey('Top', on_delete=models.CASCADE, verbose_name='Тип двигателя:')
    priv = models.ForeignKey('Priv', on_delete=models.CASCADE, verbose_name='Привод:')
    sost = models.ForeignKey('Sost', on_delete=models.CASCADE, verbose_name='Состояние:')
    ls = models.IntegerField(verbose_name='Л.С')
    pts = models.ForeignKey('Pts', on_delete=models.CASCADE, verbose_name='ПТС:')
    vlad = models.IntegerField(verbose_name='Кол-во владельцев:')
    uchet = models.ForeignKey('Uchet', on_delete=models.CASCADE, verbose_name='Стоит на учёте:')
    tel = models.CharField(verbose_name='Номер телефона для связи:', max_length=12, null=True, blank=True)
    photo1 = models.ImageField(verbose_name='Фото:', upload_to='photos/%Y/%m/%d')
    photo2 = models.ImageField(verbose_name='Фото:', upload_to='photos/%Y/%m/%d', null=True, blank=True)
    photo3 = models.ImageField(verbose_name='Фото:', upload_to='photos/%Y/%m/%d', null=True, blank=True)
    slug = models.SlugField(verbose_name="URL ОБЯЗАТЕЛЬНО! отображение на сайте", max_length=255, unique=True, db_index=True, null=True, blank=True)
    opis = models.CharField(verbose_name='Описание:', max_length=22211)
    # slug = RandomSlugField(length=7)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, null=True, blank=True)

    @property
    def formatted_number(self):
        return self.price

    class Meta:
        managed = True
        db_table = 'cars'



    def generate_random_slug(self, string_length=8):
        random_string = ''.join(random.choices(string.ascii_lowercase + string.digits, k=string_length))
        return random_string

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_random_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.model}'
    # def __str__(self):
    #     formatted_number = '{:,}'.format(self.probeg)
    #     return str(formatted_number)
    #
    # # def get_formatted_probeg(self):
    # #     formatted_probeg = '{:,}'.format(self.probeg)
    # #     return formatted_probeg

    class Meta:
        verbose_name = 'Автомобили'                       # Названия страниц в админке
        verbose_name_plural = 'Автомобили'
        # ordering = ['id']                                   # Для сортировки в таблице админпанели

    # def __str__(self):
    #     return f'{self.probeg}'

    def get_absolute_url(self):
        return reverse('car', kwargs={'car_slug': self.slug})

    # def get_formatted_price(self):
    #     formatted_price = '{:,}'.format(self.price)
    #     return formatted_price

class Marka(models.Model):                                    #Country
    name = models.CharField(verbose_name='Марка:', max_length=40)

    class Meta:
        verbose_name = 'Марки'                       # Названия страниц в админке
        verbose_name_plural = 'Марки'

    def __str__(self):
        return self.name


class Model(models.Model):                                           #City
    marka = models.ForeignKey(Marka, on_delete=models.CASCADE, verbose_name='Марка:')
    name = models.CharField(verbose_name='Модель:', max_length=40)

    class Meta:
        verbose_name = 'Модели'  # Названия страниц в админке
        verbose_name_plural = 'Модели'

    def __str__(self):
        return self.name


class Person(models.Model):
    marka = models.ForeignKey(Marka, on_delete=models.SET_NULL, blank=True, null=True)
    model = models.ForeignKey(Model, on_delete=models.SET_NULL, blank=True, null=True)

class Cuzov(models.Model):                                           #City
    cuzov = models.CharField(verbose_name='Тип кузова:', max_length=40)

    class Meta:
        verbose_name = 'Тип кузова'  # Названия страниц в админке
        verbose_name_plural = 'Тип кузова'

    def __str__(self):
        return self.cuzov

class Data(models.Model):                                           #City
    data = models.CharField(verbose_name='Год выпуска:', max_length=40)

    class Meta:
        verbose_name = 'Год выпуска'  # Названия страниц в админке
        verbose_name_plural = 'Год выпуска'

    def __str__(self):
        return self.data

class Trans(models.Model):                                           #City
    trans = models.CharField(verbose_name='Трансмисия:', max_length=40)

    class Meta:
        verbose_name = 'Трансмисия'  # Названия страниц в админке
        verbose_name_plural = 'Трансмисия'

    def __str__(self):
        return self.trans

class Obem(models.Model):
    obem = models.CharField(verbose_name='Объём двигателя:', max_length=40)

    class Meta:
        verbose_name = 'Объём двигателя'  # Названия страниц в админке
        verbose_name_plural = 'Объём двигателя'

    def __str__(self):
        return self.obem

class Top(models.Model):
    top = models.CharField(verbose_name='Тип двигателя:', max_length=40)

    class Meta:
        verbose_name = 'Тип двигателя'  # Названия страниц в админке
        verbose_name_plural = 'Тип двигателя'

    def __str__(self):
        return self.top

class Priv(models.Model):
    priv = models.CharField(verbose_name='Привод:', max_length=40)

    class Meta:
        verbose_name = 'Привод'  # Названия страниц в админке
        verbose_name_plural = 'Привод'

    def __str__(self):
        return self.priv

class Sost(models.Model):
    sost = models.CharField(verbose_name='Состояние:', max_length=40)

    class Meta:
        verbose_name = 'Состояние'  # Названия страниц в админке
        verbose_name_plural = 'Состояние'

    def __str__(self):
        return self.sost

class Pts(models.Model):
    pts = models.CharField(verbose_name='ПТС:', max_length=40)

    class Meta:
        verbose_name = 'ПТС'  # Названия страниц в админке
        verbose_name_plural = 'ПТС'

    def __str__(self):
        return self.pts

class Uchet(models.Model):
    uchet = models.CharField(verbose_name='Учёт:', max_length=40)

    class Meta:
        verbose_name = 'Учёт'  # Названия страниц в админке
        verbose_name_plural = 'Учёт'

    def __str__(self):
        return self.uchet

# class Marki(models.Model):                                                              #Group
#     name = models.CharField(verbose_name='Марка', max_length=15, null=True, blank=True)
#     objects = models.Manager()
#
#     class Meta:
#         verbose_name = 'Марка'
#         verbose_name_plural = 'Марка'
#         ordering = ['name']
#
#     def __str__(self):
#         return (f'{self.name}')
#
#
# class Model(models.Model):                                                               #Subject
#     mod = models.CharField(verbose_name='Модель', max_length=20, null=True, blank=True)
#     name = models.ManyToManyField('Marki', verbose_name='Марка')
#     # cars = models.ManyToManyField(Cars, through='Gradebook', verbose_name='Авто')
#     objects = models.Manager()
#
#     class Meta:
#         verbose_name = 'Модель'
#         verbose_name_plural = 'Модель'
#
#     def __str__(self):
#         return self.mod
#
# class Gradebook(models.Model):
#     model = models.ForeignKey(Model, on_delete=models.CASCADE, verbose_name='Модель')
#     objects = models.Manager()
#
#     class Meta:
#         verbose_name = 'Авто'
#         verbose_name_plural = 'Авто'
#
#     def __str__(self):
#         return f'{self.model}'

catalog/cars/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from cars.models import Cars, Marka, Model


class AddCarForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['group'].empty_label = 'Не выбрана'

    class Meta:
        model = Cars
        fields = ['marka', 'model', 'cuzov', 'cvet', 'vin', 'compl', 'data', 'price', 'probeg', 'trans',
                  'obem','top','priv','sost','ls','pts','vlad','uchet','tel','photo1','photo2','photo3','opis']

    # def clean_marka(self):
    #     cvet = self.cleaned_data['cvet']
    #     if not cvet.isalpha():
    #         raise ValidationError('Недопустимые символы')
    #     return cvet

# class AddCarForm2(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         # self.fields['har'].empty_label = 'Не выбрана'
#
#     class Meta:
#         model = Har
#         fields = ['trans', 'obem', 'top', 'priv', 'ls']
#
#     def clean_trans(self):
#         trans = self.cleaned_data['trans']
#         if not trans.isalpha():
#             raise ValidationError('Недопустимые символы')
#         return trans

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя')
    # email = forms.EmailField(label='E-mail')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

# class FilterCarsForm(forms.Form):
#     group = forms.ModelChoiceField(label='Модель', queryset=Marki.objects.all(), empty_label='', required=False)
#     cuzov = forms.CharField(label='Кузов', max_length=50, required=False)
#
# class ChooseMarkiForm(forms.Form):
#     group = forms.ModelChoiceField(label='Марка', queryset=Marki.objects.all(), empty_label='Не выбрана', required=False)
#
# class ChooseModelForm(forms.Form):
#     def __init__(self, *args, **kwargs):
#         self.group = kwargs.pop('group', None)
#         super(ChooseModelForm, self).__init__(*args, **kwargs)
#         if self.group:
#             group = Marki.objects.filter(id=self.group)[0]
#             self.fields['model'].queryset = group.model_set.all()
#
#     model = forms.ModelChoiceField(label='Модель', queryset=Model.objects.none(), empty_label='Не выбрана', required=False)

catalog/cars/templates/Cars/about.html
{% extends 'cars/base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
<h2 style="text-align: center;"> Лайт Авто - молодая российская динамично развивающаяся компания.</h2>
<p style="text-align: center;margin-right: 169px;margin-left: 169px;font-size: larger;">Наша компания работает открыто и честно, без лишних дополнительных платежей.
    Все расчёты подробно расписаны, полный отчет за каждый финансовый процесс.
    Работаем напрямую с Кореей, поэтому у нас одна из самых быстрых доставок!
    Также наша компания славится конкретной фиксированной комиссией и мы не берем дополнительных "скрытых платежей".
    Вы всегда сможете взять калькулятор и самостоятельно рассчитать полную стоимость автомобиля.
</p>
<!--    <p> Всего машин : {{ cars | length  }} </p>-->
{% endblock content %}

catalog/cars/templates/Cars/addcar.html
<!DOCTYPE html>
<!--{% load static %}-->
<!--<html>-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Предложить автомобиль</title>-->
<!--    <link rel="shortcut icon" href="{% static 'cars/images/logo.ico' %}" type="image/x-icon"/>-->
<!--</head>-->
<!--<body background="https://phonoteka.org/uploads/posts/2021-05/1621005305_9-phonoteka_org-p-fon-dlya-saita-s-mashinami-9.jpg">-->

<!--<h2 style="text-align-last: center;">  Добавление автомобиля:</h2>-->
<!--<form action="{% url 'addcar' %}" method="post" enctype="multipart/form-data">-->
<!--    <ul>-->
<!--        {% csrf_token %}-->
<!--        {{ form.as_p }}-->
<!--    </ul>-->
<!--    <button type="submit">Предложить авто</button>-->
<!--    </form>-->
<!--</body>-->
<!--</html>-->
<!--style="width: 285px;margin: 23px;background-color: #f5f5f5;border-radius: 54px;list-style-type: none;padding: 15px;clear: both;text-align: center;float: left;border: groove;position: absolute;top: 5%;left: 38.3%;"-->
{% block content %}
<html>
<head>
<style>

#id_marka{
    padding-right: 598px;
    padding-bottom: 20px;
    margin-top: 4px;
    background: #f1f1f1;
    border-top-style: solid;
    border-left-style: solid;
}
#id_model{
    padding-right: 601px;
    padding-bottom: 20px;
    margin-top: 4px;
    background: #f1f1f1;
    border-top-style: solid;
    border-left-style: solid;
}
#id_cuzov{
    padding-right: 563px;
    padding-bottom: 20px;
    margin-top: 4px;
    background: #f1f1f1;
    border-top-style: solid;
    border-left-style: solid;
}
#id_data{
    padding-right: 601px;
    padding-bottom: 20px;
    margin-top: 4px;
    background: #f1f1f1;
    border-top-style: solid;
    border-left-style: solid;
}
#id_trans{
    padding-right: 586px;
    padding-bottom: 20px;
    margin-top: 4px;
    background: #f1f1f1;
    border-top-style: solid;
    border-left-style: solid;
}
#id_obem{
    padding-right: 601px;
    padding-bottom: 20px;
    margin-top: 4px;
    background: #f1f1f1;
    border-top-style: solid;
    border-left-style: solid;
}
#id_top{
    padding-right: 596px;
    padding-bottom: 20px;
    margin-top: 4px;
    background: #f1f1f1;
    border-top-style: solid;
    border-left-style: solid;
}
#id_priv{
    padding-right: 586px;
    padding-bottom: 20px;
    margin-top: 4px;
    background: #f1f1f1;
    border-top-style: solid;
    border-left-style: solid;
}
#id_sost{
    padding-right: 588px;
    padding-bottom: 20px;
    margin-top: 4px;
    background: #f1f1f1;
    border-top-style: solid;
    border-left-style: solid;
}
#id_uchet{
    padding-right: 602px;
    padding-bottom: 20px;
    margin-top: 4px;
    background: #f1f1f1;
    border-top-style: solid;
    border-left-style: solid;
}
#id_pts{
    padding-right: 565px;
    padding-bottom: 20px;
    margin-top: 4px;
    background: #f1f1f1;
    border-top-style: solid;
    border-left-style: solid;
}
#id_price {
  padding-right: 5px;
  padding-left: 6px;
  display: inline-block;
  height: 40px;
  width: 672px;
  background: #f1f1f1;
  border-top-style: solid;
  border-left-style: solid;
  margin-top: 4px;
}
#id_probeg {
  padding-right: 5px;
  padding-left: 6px;
  display: inline-block;
  height: 40px;
  width: 672px;
  background: #f1f1f1;
  border-top-style: solid;
  border-left-style: solid;
  margin-top: 4px;
}
#id_ls {
  padding-right: 5px;
  padding-left: 6px;
  display: inline-block;
  height: 40px;
  width: 672px;
  background: #f1f1f1;
  border-top-style: solid;
  border-left-style: solid;
  margin-top: 4px;
}
#id_vlad {
  padding-right: 5px;
  padding-left: 6px;
  display: inline-block;
  height: 40px;
  width: 672px;
  background: #f1f1f1;
  border-top-style: solid;
  border-left-style: solid;
  margin-top: 4px;
}
#id_photo1 {
    background: #f1f1f1;
    padding: 13px 20px;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
    margin-top: 4px;
}
#id_photo2 {
    background: #f1f1f1;
    padding: 13px 20px;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
    margin-top: 4px;
}
#id_photo3 {
    background: #f1f1f1;
    padding: 13px 20px;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
    margin-top: 4px;
}
#id_opis {
    padding-right: 16px;
    height: 166px;
}

body {
    font-family: Arial, Helvetica, sans-serif;
    background-color: black;

}

* {
    box-sizing: border-box;

}


/* Add padding to containers */
.container {
    padding: 16px;
    background-color: white;

}

/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 15px;
    margin: 5px 0 0px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
    background-color: #ddd;
    outline: none;
}

/* Overwrite default styles of hr */
hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
    background-color: #384c76;
    color: white;
    padding: 16px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
}

.registerbtn:hover {
    opacity: 1;
}

/* Add a blue text color to links */
a {
    color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
    background-color: #f1f1f1;
    text-align: center;
}
</style>
</head>
<body background="https://phonoteka.top/uploads/posts/2021-05/1619823165_6-phonoteka_org-p-fon-dlya-saita-avtomobilnoi-tematiki-7.jpg">
<form action="{% url 'addcar' %}" method="post" enctype="multipart/form-data">
  <div class="container" style="margin-left: 400px;margin-right: 400px;margin-top: 20px;">
    <h2 style="text-align: center;">Добавление автомобиля</h2>
  {% csrf_token %}
  {{ form.as_p }}
    <button type="submit" class="registerbtn">Предложить</button>
  </div>
</form>
</body>
</html>

{% endblock %}

catalog/cars/templates/Cars/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru" >
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>

    <h1>Л а й т - А в т о</h1>
    <link type="text/css" href="{% static 'cars/css/styles.css' %}" rel="stylesheet" />
</head>
<body background="https://phonoteka.top/uploads/posts/2021-05/1619823165_6-phonoteka_org-p-fon-dlya-saita-avtomobilnoi-tematiki-7.jpg">
  {% block mainmenu %}
  <div class="header">
  <ul id="mainmenu" class="mainmenu">
      <li class="logo">
          <img src="https://s.auto.drom.ru/i24280/dealers/dealer/desc/114511/gen380_282a98d8-d104-439e-82b3-6f5c6441b3fc.jpg" width="80" height="40" align="middle" alt="Лого" class="leftimg"><a href="tel:+79200719107">+7 (920) 071-91-07</a>
          <a href="{% url 'auto' %}"><div class="logo"></div></a></li>
    {% for m in menu %}
        <li><a href="{% url m.url_name %}">{{ m.title }}</a></li>
    {% endfor %}
      {% if request.user.is_authenticated %}
        <li class="last"> <a href="{% url 'addcar' %}">Предложить авто</a> | {{user.username}} | <a href="{% url 'logout' %}">Выйти</a> </li>
      {% else %}
        <li class="last"><a href="{% url 'register' %}">Регистрация</a> | <a href="{% url 'login' %}"> Войти</a></li>
      {% endif %}
  </ul>
  </div>
  {% endblock mainmenu %}
  {% block content %}
  {% endblock content %}
</body>
</html>

catalog/cars/templates/Cars/car.html
{% extends 'cars/base.html' %}

{% block content %}
<h1>{{ st.marka }} {{ st.model }} {{ st.cuzov }}</h1>
  <style>
   .leftimg {
    float:left; /* Выравнивание по левому краю */
    margin: 0px 15px 15px 0; /* Отступы вокруг картинки */
   }
   .rightimg  {
    float: right; /* Выравнивание по правому краю  */
    margin: 7px 0 7px 7px; /* Отступы вокруг картинки */
   }
  </style>
{% if ca.photo1 %}
    <img src="{{ ca.photo1.url }}"width="490" height="350" alt="Cars photo" class="leftimg" />
{% endif %}
{% if ca.photo2 %}
    <img src="{{ ca.photo2.url }}"width="490" height="350" alt="Cars photo" class="leftimg" />
{% endif %}
{% if ca.photo3 %}
    <img src="{{ ca.photo3.url }}"width="490" height="350" alt="Cars photo" class="leftimg" />
{% endif %}
<div style="width: fit-content;background-color: rgba(20, 20, 20, 0.5);">

 <ul style="padding-left: 530px;list-style-type: none;font-size: larger;line-height: 2;color: white;"><p >
   <li> <b style="color: #D5D5D5">Марка:  </b> {{ca.marka }}</li>
<li><b style="color: #D5D5D5">Модель:</b> {{ca.model }}<br /></li>
<li><b style="color: #D5D5D5">Кузов:</b> {{ca.cuzov }}</li>
<li><b style="color: #D5D5D5">Цвет:</b> {{ca.cvet }}<br /></li>
<li><b style="color: #D5D5D5">Дата производства:</b> {{ca.data }} год</li>
</ul>
     <ul style="position: absolute;width: 524.983px;padding-left: 819px;top: 510.7px;list-style-type: none;font-size: larger;line-height: 2;color: white;"><li><b style="color: #D5D5D5">ПТС:</b> {{ca.pts }}<br /></li>
<li><b style="color: #D5D5D5">Пробег:</b> {{ca.probeg }} км.</li>
<li><b style="color: #D5D5D5">Владельцев:</b> {{ca.vlad }}<br /></li>
<li><b style="color: #D5D5D5">Цена:</b> {{ca.price }} р.</li>
     <li><b style="color: #D5D5D5"> Характеристики:</b> {{ca.obem }}/{{ca.trans }}/{{ca.priv }}/{{ca.ls }}л.с./{{ca.top }}<br /></li>
         </ul>
<ul><li style="font-size: larger;margin-right: 42px;list-style-type: none;color: white;background-color: rgba(20, 20, 20, 0.8);text-align: center;"><b style="color: #D5D5D5">Описание:</b><br /> {{ca.opis }}</li></p>
     </ul>

</div>
{% endblock %}

catalog/cars/templates/Cars/contacts.html
{% extends 'cars/base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
<h2 style="text-align: center;"> Лайт Авто</h2>
<p style="text-align: center;font-size: larger;">Адрес: Московское ш., 318г, Нижний Новгород, Нижегородская обл., 603092<br />
Часы работы:<br />
пятница	10:00–20:00<br />
суббота	10:00–20:00<br />
воскресенье	10:00–20:00<br />
понедельник	10:00–20:00<br />
вторник	10:00–20:00<br />
среда	10:00–20:00<br />
четверг	10:00–20:00<br />
<br />
Телефон: 8 (920) 071-91-07
</p>
{% endblock content %}

catalog/cars/templates/Cars/gradebook.html
<!--{% extends 'cars/base.html' %}-->

<!--{% block content %}-->
<!--<h1>{{ title }}</h1>-->
<!--<br>-->
<!--<form method="get" action="{% url 'gradebook' %}">-->
<!--    {{ group_form }}-->
<!--    <button type="submit">Выбрать</button>-->
<!--</form>-->
<!--{% if group %}-->
<!--    <form method="get" action="{% url 'gradebook' %}">-->
<!--        {{ subj_form }}-->
<!--        <input type="hidden" name="group" value="{{ group }}" />-->
<!--        <button type="submit">Выбрать</button>-->
<!--    </form>-->
<!--{% endif %}-->
<!--<br>-->
<!--{% endblock %}-->